name: CI
on:
  pull_request:
  push:
    branches:
      - foxy-devel
  schedule:
    # every Monday
    - cron:  '0 0 * * 1'

jobs:
  build:
    runs-on: [ubuntu-20.04]
    strategy:
      fail-fast: false
      matrix:
        ROSDISTRO: [foxy]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        path: src
    - name: Install
      shell: bash
      run: |
        sudo apt update && sudo apt install curl gnupg2 lsb-release
        curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
        sudo apt update
        sudo apt install ros-foxy-desktop
        source /opt/ros/foxy/setup.bash
        sudo apt install python3-colcon-common-extensions
      env:
        ROSDISTRO: ${{ matrix.ROSDISTRO }}
    - name: Configure Microsoft's Package Repository
      shell: bash
      continue-on-error: true 
      run: |
        curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        sudo apt-add-repository https://packages.microsoft.com/ubuntu/18.04/prod
    - name: Continue Configuring Microsoft's Package Repository
      shell: bash
      continue-on-error: true 
      run: |
        curl -sSL https://packages.microsoft.com/config/ubuntu/18.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft-prod.list
        curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        sudo apt-get update
    - name: Install Azure Kinect Sensor SDK
      shell: bash
      run: |
        export DEBIAN_FRONTEND=noninteractive
        echo 'libk4a1.3 libk4a1.3/accepted-eula-hash string 0f5d5c5de396e4fee4c0753a21fee0c1ed726cf0316204edda484f08cb266d76' | sudo debconf-set-selections
        echo 'libk4a1.3 libk4a1.3/accept-eula boolean true' | sudo debconf-set-selections
        sudo apt install libk4a1.3-dev
        sudo apt install k4a-tools=1.3.0
    - name: Build
      shell: bash
      run: |
        source /opt/ros/foxy/setup.bash
        colcon build --packages-select azure_kinect_ros_driver --event-handlers console_cohesion+
      env:
        ROSDISTRO: ${{ matrix.ROSDISTRO }}